document.addEventListener('DOMContentLoaded', () => {
  const account = JSON.parse(localStorage.getItem('karachiMartAccount') || 'null'); if (!account || localStorage.getItem('karachiMartLoggedIn') !== 'true') { window.location.href = 'login.html'; return; }
  document.getElementById('profile-name').textContent = account.name; document.getElementById('profile-email').textContent = account.email; document.getElementById('profile-avatar').textContent = account.name.slice(0, 2).toUpperCase();
  document.getElementById('profile-logout').addEventListener('click', () => { localStorage.removeItem('karachiMartLoggedIn'); localStorage.removeItem('karachiMartUser'); localStorage.removeItem('karachiMartEmail'); window.location.href = 'index.html'; });
  const photoInput = document.getElementById('profile-photo'); const photoMessage = document.getElementById('photo-message'); const avatar = document.getElementById('profile-avatar'); const savedPhoto = localStorage.getItem('karachiMartPhoto'); if (savedPhoto) setPhoto(savedPhoto);
  photoInput.addEventListener('change', () => { const file = photoInput.files[0]; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { photoMessage.textContent = 'Choose JPG, PNG or WebP up to 5 MB.'; return; } const reader = new FileReader(); reader.onload = () => { localStorage.setItem('karachiMartPhoto', reader.result); setPhoto(reader.result); photoMessage.textContent = 'Profile photo updated.'; }; reader.readAsDataURL(file); });
  document.getElementById('remove-photo').addEventListener('click', () => { localStorage.removeItem('karachiMartPhoto'); avatar.textContent = account.name.slice(0, 2).toUpperCase(); avatar.style.backgroundImage = ''; photoMessage.textContent = 'Profile photo removed.'; });
  function setPhoto(url) { avatar.textContent = ''; avatar.style.backgroundImage = `url("${url}")`; }
  const order = JSON.parse(localStorage.getItem('karachiMartOrder') || 'null'); document.getElementById('total-orders').textContent = order ? '1' : '0'; document.getElementById('total-purchases').textContent = order ? `Rs. ${order.total.toLocaleString()}` : 'Rs. 0'; document.getElementById('order-history').innerHTML = order ? `<div class="history-row"><strong>${order.id}</strong><span>${order.status}</span><b>Rs. ${order.total.toLocaleString()}</b></div>` : '<p class="muted">No purchases yet.</p>';
  avatar.addEventListener('click', () => { const url = localStorage.getItem('karachiMartPhoto'); if (!url) return; document.getElementById('photo-preview').src = url; document.getElementById('photo-modal').hidden = false; }); document.getElementById('close-photo').addEventListener('click', () => { document.getElementById('photo-modal').hidden = true; });
});